# Configuration File for the MODIS/SLSTR/OLCI/VIIRS file retrieval wrapper
meta:
    # meta information on sensor/carrier [MODIS/SLSTR/OLCI/VIIRS; terra/aqua/s3a/s3b/snpp/jpss1], 
    # aois [as python list, e.g., [berkner, brunt, dibble]], the aoi scale factor derivating 
    # from the nominal 1km x 1km reslution of the grids, and its meta-data version
    # [full/production/experimental] to be used
    sensor: MODIS
    carrier: terra
    aoi: [berkner, brunt, dibble]
    scale: 1.0
    version: production

io:
    # Input/Output handlers depending on the file type of the swath data
    # [{HDF4/HDF5/NetCDF}Swath{Input/Output}]
    input: HDF4SwathInput
    output: HDF5SwathOutput
    # output path for the retrieved data [will be created if not existent]
    path: C:\data\testretrieval
    
authentication:
    # LAADS authentication token
    token: 

date:
    # start and end date of the processing [yyyy-mm-dd]
    start: 2020-09-01
    stop:  2020-10-31

listing:
    # Listing is always applied but the necessary modules need to be specified,
    # while the sensor-specific version will be chosen automatically
    # - ListingProcessHandler
    # - ListingRetrievalHandler
    override: False
    modules: 
        process: ListingProcessHandler
        retrieval: ListingRetrievalHandler

retrieval:
    # Specify whether file retrieval should be performed [True/False] as well as
    # the necessary modules, with sensor-specific versions will be chosen automatically
    # - SwathHandler
    # - RetrievalHandler
    apply: True
    modules:
        swath: SwathHandler
        retrieval: RetrievalHandler
    
resampling:
    # Specify whether resampling should be performed [True/False] using the 
    # given module
    apply: True
    modules: 
        base: Resampling