# Configuration File for the MODIS/SLSTR/OLCI file retrieval wrapper
meta:
    # meta information on sensor/carrier [MODIS/SLSTR/OLCI/VIIRS; terra/aqua/s3a/s3b], 
    # aois [as python list, e.g., [berkner, brunt, dibble]], and its meta-data version
    # [full/production/experimental] to be used
    sensor: MODIS
    carrier: terra
    aoi: [berkner, brunt, dibble]
    version: prod-v1p0

output:
    # output path for the retrieved data [will be created if not existent]
    path: C:\data\testretrieval
    
authentication:
    # LAADS authentication token
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJBUFMgT0F1dGgyIEF1dGhlbnRpY2F0b3IiLCJpYXQiOjE2ODg1NzkwMjMsIm5iZiI6MTY4ODU3OTAyMywiZXhwIjoxNzA0MTMxMDIzLCJ1aWQiOiJzcGF1bDExODQiLCJlbWFpbF9hZGRyZXNzIjoic3RlcGhhbi5wYXVsQGF3aS5kZSIsInRva2VuQ3JlYXRvciI6InNwYXVsMTE4NCJ9.95ETGa97zgqbcRAblKNGCr81gpJnf19rNT0tdJVG5VM

date:
    # start and end date of the processing [yyyy-mm-dd]
    start: 2020-09-01
    stop:  2020-09-01

processing:
    # processing modules to be used and loaded for the job [True/False]
    listing: 
        name: ModisListing
    retrieval: 
        name: ModisRetrieval
        apply: True
    resampling: 
        name: Resampling
        apply: True